public class Constants {
    public static final String QUOTE_ICAO_MAIL_SUBJECT = 'Unmatched ICAO Codes from CSV Upload';
    public static final String SD_PS_NAME = 'SalesBaseCPQUser';
    public static final String CSV_COL_HEADING_ICAO_NUMBER = 'ICAO number';
    public static final String NO_MATCHING_ICAO= 'CSV contains no ICAO numbers';
    public static final String PS_LICENSE_SF_CPQ_LICENSE = 'Salesforce CPQ License';
    public static final String SD_USER_ROLE = 'Commercial Aviation Sales Director  - Europe (Western)';
    public static final String SD_PROFILE_NAME = 'Flightpath Base Profile';
    public static final String CONST_TEST = 'Test';
    public static final String CONST_SALES_DIRECTOR = 'SalesDirector';
    public static final String CONST_SD_EMAIL = 'salesdirector@example.com';
    public static final String CONST_SD_USERNAME = 'salesdirector.testuser@example.com.test';
    public static final String CONST_SD_ALIAS = 'sdir';

}
